export const initialOrganizations = [
  {
    id: 'org-northwind',
    name: 'Northwind Academy',
    email: 'ops@northwind.edu',
    phone: '+1 (555) 104-2200',
    address: '12 Harbor Avenue, Seattle',
    logoUrl: '',
    status: 'active',
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'org-summit',
    name: 'Summit Health Institute',
    email: 'admin@summithealth.org',
    phone: '+1 (555) 938-1100',
    address: '88 Crest Park, Denver',
    logoUrl: '',
    status: 'active',
    createdAt: '2026-01-18T09:00:00.000Z',
  },
  {
    id: 'org-pioneer',
    name: 'Pioneer Training Center',
    email: 'hello@pioneertraining.co',
    phone: '+1 (555) 410-8910',
    address: '5 Market Lane, Austin',
    logoUrl: '',
    status: 'inactive',
    createdAt: '2026-02-04T09:00:00.000Z',
  },
]

export const initialDepartments = [
  {
    id: 'dept-cs',
    organizationId: 'org-northwind',
    name: 'Computer Science',
    description: 'Lecture and lab attendance for degree cohorts.',
    createdAt: '2026-01-11T09:00:00.000Z',
  },
  {
    id: 'dept-data',
    organizationId: 'org-northwind',
    name: 'Data Science Lab',
    description: 'Applied analytics labs and capstone workshops.',
    createdAt: '2026-01-13T09:00:00.000Z',
  },
  {
    id: 'dept-nursing',
    organizationId: 'org-summit',
    name: 'Emergency Nursing',
    description: 'Shift-based clinical practical attendance monitoring.',
    createdAt: '2026-01-20T09:00:00.000Z',
  },
  {
    id: 'dept-public-health',
    organizationId: 'org-summit',
    name: 'Public Health',
    description: 'Community health rotations and theory sessions.',
    createdAt: '2026-01-22T09:00:00.000Z',
  },
  {
    id: 'dept-ops',
    organizationId: 'org-pioneer',
    name: 'Operations Trainees',
    description: 'Instructor-led safety and logistics workshops.',
    createdAt: '2026-02-05T09:00:00.000Z',
  },
]

export const initialUsers = [
  {
    id: 'user-super-mia',
    authUserId: 'auth-super-mia',
    organizationId: null,
    departmentId: null,
    firstName: 'Mia',
    lastName: 'Reynolds',
    email: 'mia.reynolds@rollog.test',
    phone: '+1 (555) 010-2200',
    role: 'super_admin',
    employeeCode: 'SA-001',
    status: 'active',
    avatarUrl: '',
    mockPassword: 'Admin123!',
    createdAt: '2026-01-05T08:00:00.000Z',
  },
  {
    id: 'user-org-arthur',
    authUserId: 'auth-org-arthur',
    organizationId: 'org-northwind',
    departmentId: null,
    firstName: 'Arthur',
    lastName: 'Blake',
    email: 'arthur.blake@northwind.edu',
    phone: '+1 (555) 410-2230',
    role: 'organization_admin',
    employeeCode: 'NW-ADM-01',
    status: 'active',
    avatarUrl: '',
    mockPassword: 'Northwind123!',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'user-org-nadine',
    authUserId: 'auth-org-nadine',
    organizationId: 'org-summit',
    departmentId: null,
    firstName: 'Nadine',
    lastName: 'Costa',
    email: 'nadine.costa@summithealth.org',
    phone: '+1 (555) 830-2210',
    role: 'organization_admin',
    employeeCode: 'SH-ADM-01',
    status: 'active',
    avatarUrl: '',
    mockPassword: 'Summit123!',
    createdAt: '2026-01-18T10:00:00.000Z',
  },
  {
    id: 'user-att-olivia',
    authUserId: 'auth-att-olivia',
    organizationId: 'org-northwind',
    departmentId: 'dept-cs',
    firstName: 'Olivia',
    lastName: 'Bennett',
    email: 'olivia.bennett@northwind.edu',
    phone: '+1 (555) 212-4101',
    role: 'attendee',
    employeeCode: 'NW-CS-1001',
    status: 'active',
    avatarUrl: '',
    mockPassword: 'Attendee123!',
    createdAt: '2026-01-12T09:00:00.000Z',
  },
  {
    id: 'user-att-noah',
    authUserId: 'auth-att-noah',
    organizationId: 'org-northwind',
    departmentId: 'dept-cs',
    firstName: 'Noah',
    lastName: 'Johnson',
    email: 'noah.johnson@northwind.edu',
    phone: '+1 (555) 401-9191',
    role: 'attendee',
    employeeCode: 'NW-CS-1002',
    status: 'inactive',
    avatarUrl: '',
    mockPassword: 'Attendee123!',
    createdAt: '2026-01-12T09:30:00.000Z',
  },
  {
    id: 'user-att-harper',
    authUserId: 'auth-att-harper',
    organizationId: 'org-northwind',
    departmentId: 'dept-data',
    firstName: 'Harper',
    lastName: 'Stone',
    email: 'harper.stone@northwind.edu',
    phone: '+1 (555) 404-3322',
    role: 'attendee',
    employeeCode: 'NW-DS-1003',
    status: 'active',
    avatarUrl: '',
    mockPassword: 'Attendee123!',
    createdAt: '2026-01-14T09:30:00.000Z',
  },
  {
    id: 'user-att-liam',
    authUserId: 'auth-att-liam',
    organizationId: 'org-summit',
    departmentId: 'dept-nursing',
    firstName: 'Liam',
    lastName: 'Carter',
    email: 'liam.carter@summithealth.org',
    phone: '+1 (555) 830-2229',
    role: 'attendee',
    employeeCode: 'SH-EN-1001',
    status: 'active',
    avatarUrl: '',
    mockPassword: 'Attendee123!',
    createdAt: '2026-01-20T09:30:00.000Z',
  },
  {
    id: 'user-att-sophia',
    authUserId: 'auth-att-sophia',
    organizationId: 'org-pioneer',
    departmentId: 'dept-ops',
    firstName: 'Sophia',
    lastName: 'Evans',
    email: 'sophia.evans@pioneertraining.co',
    phone: '+1 (555) 180-7714',
    role: 'attendee',
    employeeCode: 'PT-OPS-1001',
    status: 'active',
    avatarUrl: '',
    mockPassword: 'Attendee123!',
    createdAt: '2026-02-06T09:30:00.000Z',
  },
  {
    id: 'user-att-zoe',
    authUserId: 'auth-att-zoe',
    organizationId: 'org-summit',
    departmentId: 'dept-public-health',
    firstName: 'Zoe',
    lastName: 'Mills',
    email: 'zoe.mills@summithealth.org',
    phone: '+1 (555) 663-2298',
    role: 'attendee',
    employeeCode: 'SH-PH-1002',
    status: 'active',
    avatarUrl: '',
    mockPassword: 'Attendee123!',
    createdAt: '2026-01-21T09:30:00.000Z',
  },
]

export const initialSessions = [
  {
    id: 'session-assembly',
    organizationId: 'org-northwind',
    departmentId: 'dept-cs',
    createdBy: 'user-org-arthur',
    title: 'Morning Assembly',
    description: 'Opening lecture attendance window for the Computer Science cohort.',
    sessionDate: '2026-03-17',
    startTime: '08:00',
    endTime: '09:00',
    graceMinutes: 10,
    attendanceMethod: 'qr',
    qrToken: 'NW-ASM-170326',
    locationRequired: false,
    latitude: null,
    longitude: null,
    radiusMeters: null,
    status: 'active',
    createdAt: '2026-03-16T18:00:00.000Z',
  },
  {
    id: 'session-clinical-lab',
    organizationId: 'org-summit',
    departmentId: 'dept-nursing',
    createdBy: 'user-org-nadine',
    title: 'Clinical Lab Rotation',
    description: 'Rotational practical session with QR check-in at the lab entrance.',
    sessionDate: '2026-03-18',
    startTime: '09:30',
    endTime: '11:30',
    graceMinutes: 15,
    attendanceMethod: 'qr',
    qrToken: 'SH-LAB-180326',
    locationRequired: true,
    latitude: 39.7392,
    longitude: -104.9903,
    radiusMeters: 150,
    status: 'draft',
    createdAt: '2026-03-15T18:00:00.000Z',
  },
  {
    id: 'session-safety',
    organizationId: 'org-pioneer',
    departmentId: 'dept-ops',
    createdBy: 'user-super-mia',
    title: 'Safety Workshop',
    description: 'Weekly operations safety briefing and compliance register.',
    sessionDate: '2026-03-15',
    startTime: '13:00',
    endTime: '15:00',
    graceMinutes: 5,
    attendanceMethod: 'qr',
    qrToken: 'PT-SAFE-150326',
    locationRequired: false,
    latitude: null,
    longitude: null,
    radiusMeters: null,
    status: 'closed',
    createdAt: '2026-03-13T17:00:00.000Z',
  },
  {
    id: 'session-capstone',
    organizationId: 'org-northwind',
    departmentId: 'dept-data',
    createdBy: 'user-org-arthur',
    title: 'Capstone Review',
    description: 'Department review session for final-year project attendance.',
    sessionDate: '2026-03-19',
    startTime: '14:00',
    endTime: '16:00',
    graceMinutes: 20,
    attendanceMethod: 'hybrid',
    qrToken: 'NW-CAP-190326',
    locationRequired: false,
    latitude: null,
    longitude: null,
    radiusMeters: null,
    status: 'draft',
    createdAt: '2026-03-16T11:30:00.000Z',
  },
]

export const initialSessionParticipants = [
  {
    id: 'participant-assembly-1',
    sessionId: 'session-assembly',
    userId: 'user-att-olivia',
    createdAt: '2026-03-16T18:05:00.000Z',
  },
  {
    id: 'participant-assembly-2',
    sessionId: 'session-assembly',
    userId: 'user-att-noah',
    createdAt: '2026-03-16T18:05:00.000Z',
  },
  {
    id: 'participant-lab-1',
    sessionId: 'session-clinical-lab',
    userId: 'user-att-liam',
    createdAt: '2026-03-15T18:05:00.000Z',
  },
  {
    id: 'participant-safety-1',
    sessionId: 'session-safety',
    userId: 'user-att-sophia',
    createdAt: '2026-03-13T17:05:00.000Z',
  },
  {
    id: 'participant-capstone-1',
    sessionId: 'session-capstone',
    userId: 'user-att-harper',
    createdAt: '2026-03-16T11:35:00.000Z',
  },
]

export const initialAttendanceRecords = [
  {
    id: 'attendance-assembly-olivia',
    sessionId: 'session-assembly',
    userId: 'user-att-olivia',
    checkInTime: '2026-03-17T08:03:00.000Z',
    status: 'present',
    method: 'qr',
    latitude: null,
    longitude: null,
    deviceInfo: 'Android 14 - Samsung A15',
    photoUrl: '',
    remarks: '',
    createdAt: '2026-03-17T08:03:00.000Z',
    updatedAt: '2026-03-17T08:03:00.000Z',
  },
  {
    id: 'attendance-assembly-noah',
    sessionId: 'session-assembly',
    userId: 'user-att-noah',
    checkInTime: '2026-03-17T08:14:00.000Z',
    status: 'late',
    method: 'manual',
    latitude: null,
    longitude: null,
    deviceInfo: 'Admin override',
    photoUrl: '',
    remarks: 'Check-in recorded manually after scanner issue.',
    createdAt: '2026-03-17T08:14:00.000Z',
    updatedAt: '2026-03-17T08:14:00.000Z',
  },
  {
    id: 'attendance-safety-sophia',
    sessionId: 'session-safety',
    userId: 'user-att-sophia',
    checkInTime: '2026-03-15T13:04:00.000Z',
    status: 'present',
    method: 'qr',
    latitude: null,
    longitude: null,
    deviceInfo: 'iOS 19 - iPhone 17',
    photoUrl: '',
    remarks: '',
    createdAt: '2026-03-15T13:04:00.000Z',
    updatedAt: '2026-03-15T13:04:00.000Z',
  },
]

export const initialAttendanceLogs = [
  {
    id: 'log-assembly-olivia',
    attendanceRecordId: 'attendance-assembly-olivia',
    action: 'QR check-in recorded',
    metadata: {
      actor: 'system',
    },
    createdAt: '2026-03-17T08:03:00.000Z',
  },
  {
    id: 'log-assembly-noah',
    attendanceRecordId: 'attendance-assembly-noah',
    action: 'Manual attendance override',
    metadata: {
      actor: 'user-org-arthur',
    },
    createdAt: '2026-03-17T08:14:00.000Z',
  },
]

export const initialNotifications = [
  {
    id: 'notification-1',
    userId: 'user-super-mia',
    title: 'Attendance threshold alert',
    message: 'Emergency Nursing dropped below the 85% attendance threshold this week.',
    tone: 'warning',
    read: false,
    createdAt: '2026-03-17T08:12:00.000Z',
  },
  {
    id: 'notification-2',
    userId: 'user-org-arthur',
    title: 'QR session ready',
    message: 'Morning Assembly is active and ready for attendee check-in.',
    tone: 'info',
    read: false,
    createdAt: '2026-03-17T07:58:00.000Z',
  },
  {
    id: 'notification-3',
    userId: 'user-org-nadine',
    title: 'Draft session needs review',
    message: 'Clinical Lab Rotation is still in draft and has not opened its QR flow.',
    tone: 'warning',
    read: false,
    createdAt: '2026-03-16T19:12:00.000Z',
  },
  {
    id: 'notification-4',
    userId: 'user-super-mia',
    title: 'Report export completed',
    message: 'The weekly organization summary bundle is available for download.',
    tone: 'success',
    read: true,
    createdAt: '2026-03-16T17:40:00.000Z',
  },
]

export const initialSettings = {
  emailNotifications: true,
  securityAlerts: true,
  dailyDigest: true,
  autoCloseSessions: false,
  requireManualReason: true,
  defaultGraceMinutes: 10,
}

export const initialPrototypeState = {
  organizations: initialOrganizations,
  departments: initialDepartments,
  users: initialUsers,
  sessions: initialSessions,
  sessionParticipants: initialSessionParticipants,
  attendanceRecords: initialAttendanceRecords,
  attendanceLogs: initialAttendanceLogs,
  notifications: initialNotifications,
  settings: initialSettings,
  auth: {
    currentUserId: null,
    verification: null,
  },
  ui: {
    selectedOrganizationId: null,
    selectedDepartmentId: null,
    selectedSessionId: null,
  },
}
